# Generated by Django 4.1.8 on 2023-05-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.area')),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(default='12345678-9', max_length=50)),
                ('cargo', models.CharField(default='RRHH', max_length=50)),
                ('password', models.CharField(default='6-qL8@_gzaG+ed+4', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('rut_trabajador', models.CharField(max_length=50)),
                ('nombre_trabajador', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('direccion_trabajador', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('id_contacto', models.CharField(max_length=100)),
                ('id_cargas_familiares', models.IntegerField()),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.area')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.cargo')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.departamento')),
            ],
        ),
    ]
